### ISSUE TITLE
NO Devies found 

### ISSUE THREAD

**Issue by sripappula** [rajdeepv/parallel_calabash#31]
I'm getting below when i run 

**parallel_calabash -app my.app --ios_config ~/.parallel_calabash.iphoneos**

/Users/***/.rvm/gems/ruby-2.3.0/gems/parallel_calabash-0.2.7.pre/lib/parallel_calabash.rb:39:in `number_of_processes_to_start':  (RuntimeError)
**** NO DEVICE FOUND ****
	from /Users/***/.rvm/gems/ruby-2.3.0/gems/parallel_calabash-0.2.7.pre/lib/parallel_calabash.rb:49:in `run_tests_in_parallel'
	from /Users/***/.rvm/gems/ruby-2.3.0/gems/parallel_calabash-0.2.7.pre/bin/parallel_calabash:99:in `<top (required)>'
	from /Users/***/.rvm/gems/ruby-2.3.0/bin/parallel_calabash:23:in `load'
	from /Users/***/.rvm/gems/ruby-2.3.0/bin/parallel_calabash:23:in `<main>'
	from /Users/***/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/***/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by rajdeepv** [comment]
@sripappula Instead of -app use --app (with double hyphen)

**Comment by sripappula** [comment]
thanks for quick reply.. i have gone pass that issue.

now i'm getting below error

*******************************
 1 DEVICES FOUND:
{:NAME=>"Sri’s iPhone", :DEVICE_TARGET=>"16886319b3d0fca513584439a071b1ff6a13e528", :DEVICE_ENDPOINT=>"http://192.168.0.11:37265", :USER=>"tester1", :INIT=>"[[ -s \"$HOME/.rvm/scripts/rvm\" ]] && source \"$HOME/.rvm/scripts/rvm\""}
*******************************
Running with 1 threads: [["features/add_debit_card.feature"]]
0>> Device: 16886319b3d0fca513584439a071b1ff6a13e528 = PCal-tester1 = 16886319b3d0fca513584439a071b1ff6a13e528
PING 192.168.0.11 (192.168.0.11): 56 data bytes
64 bytes from 192.168.0.11: icmp_seq=0 ttl=64 time=74.768 ms

--- 192.168.0.11 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 74.768/74.768/74.768/0.000 ms
0>> Command: ssh tester1@localhost bash -lc "AUTOTEST='1';export AUTOTEST;DEVICE_ENDPOINT='http://192.168.0.11:37265';export DEVICE_ENDPOINT;DEVICE_TARGET='16886319b3d0fca513584439a071b1ff6a13e528';export DEVICE_TARGET;DEVICE_INFO='16886319b3d0fca513584439a071b1ff6a13e528';export DEVICE_INFO;TEST_USER='tester1';export TEST_USER;TEST_PROCESS_NUMBER='1';export TEST_PROCESS_NUMBER;SCREENSHOT_PATH='PCal_1_';export SCREENSHOT_PATH;[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm";cd /Users/***/workspace/cardapp_ui_tests;umask 002;bundle exec cucumber APP_BUNDLE_PATH=build/Applications/Badoo.app   features/add_debit_card.feature" 2>&1
Password:
**0> Permission denied @ rb_sysopen - out.log (Errno::EACCES)**

****** PROCESS 0 COMPLETED ******

Writing log /tmp/PCal-tester1.process_number
[0]
All threads complete

I have done this step as well 
**Copy ~main_account/.ssh/id_rsa.pub into each test account's ~tester1/.ssh/authorized_keys**

can you please let me know the solution for the above permission denied error

Let me know if you need any further info

thank you,
sri

**Comment by sripappula** [comment]
Also i have ssh access to my test machine.
